FROM fedora:rawhide
RUN yum update -y && yum install -y clang llvm-devel zlib-devel
ENV CARGO_HOME /usr/local
ENV RUSTUP_HOME /usr/local
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ARG KERNEL_HEADERS_TAR
ADD $KERNEL_HEADERS_TAR /
ARG REDBPF_TAR
ADD $REDBPF_TAR /
WORKDIR /redbpf
CMD cargo build
