name: RedBPF build

on:
  push:
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/redbpf
  MAIN_BRANCH: main

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-20.04, fedora-35]
        env:
        - IMAGE_TAG: ubuntu-20.04
        - IMAGE_TAG: fedora-35
    steps:
    - uses: actions/checkout@v2
    - name: System info
      run: |
        uname -a
        lsb_release -a
    - name: Build docker image for building RedBPF
      env: ${{ matrix.env }}
      run: |
        git submodule update --init --recursive
        docker build -t redbpf-build -f Dockerfile.${IMAGE_TAG} .
    - name: Run RedBPF build
      run: |
        docker run --privileged \
        -v /sys/kernel/debug:/sys/kernel/debug:rw \
        -v /lib/modules:/lib/modules:ro \
        -v /usr/src:/usr/src:ro \
        -v /usr/include/linux:/usr/include/linux:ro \
        redbpf-build
