name: RedBPF build

on:
  push:
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  ubuntu-2004-build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: System info
      run: |
        uname -a
        lsb_release -a
    - name: Initialize git submodules
      run: |
        git submodule update --init --recursive
    - name: Run RedBPF build on ubuntu-20.04 container
      run: |
        docker run --privileged \
        -v /sys/kernel/debug:/sys/kernel/debug:rw \
        -v /lib/modules:/lib/modules:ro \
        -v /usr/src:/usr/src:ro \
        -v /usr/include/linux:/usr/include/linux:ro \
        -v .:/build \
        ghcr.io/rhdxmr/ingraind-build:latest-ubuntu-20.04 \
        /bin/bash -c "cargo build && cargo build --examples"

  fedora-35-build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: System info
      run: |
        uname -a
        lsb_release -a
    - name: Initialize git submodules
      run: |
        git submodule update --init --recursive
    - name: Run RedBPF build on fedora-35 container
      run: |
        docker run --privileged \
        -v /sys/kernel/debug:/sys/kernel/debug:rw \
        -v /lib/modules:/lib/modules:ro \
        -v /usr/src:/usr/src:ro \
        -v /usr/include/linux:/usr/include/linux:ro \
        -v .:/build \
        ghcr.io/rhdxmr/ingraind-build:latest-fedora-rawhide \
        /bin/bash -c "cargo build && cargo build --examples"
